export const DASHBOARD = '/'
export const PRESCRIPTION = '/prescription/:hash'
export const HEADER = '/'
export const SETTINGS = '/private/settings'
export const LOGIN = '/login'
export const CREATE_ACCOUNT = '/account'
