export const DASHBOARD = '/private/dashboard'
export const RECIPE = '/private/recipe/:hash'
export const HEADER = '/private'
export const SETTINGS = '/private/settings'
export const LOGIN = '/'
export const CREATE_ACCOUNT = '/account'
