export const DASHBOARD = '/'
export const RECIPE = '/recipe/:hash'
export const HEADER = '/'
export const SETTINGS = '/private/settings'
export const LOGIN = '/login'
export const CREATE_ACCOUNT = '/account'
